apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-apps
  namespace: argocd
spec:
  generators:
    # Generator for apps that should deploy to chosen cluster.
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: dev
          - clusters:
              selector:
                matchLabels:
                  env: stg
          - list:
              elements:
              - appName: metrics-server
                namespace: kube-system
              - appName: ingress-nginx
                namespace: ingress-nginx
  template:
    metadata:
      name: "{{name}}-{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: bootstrap
      source:
        repoURL: https://github.com/fitsnips/argocd-layout-testing
        targetRevision: HEAD
        path: "charts/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - "values.yaml"
          - "../../values/{{name}}/{{appName}}/values.yaml"
      destination:
        name: "{{name}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 2